// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGajcFJDnxFwCyg1C7HW9iQtb-ElZilts',
    appId: '1:669691510276:web:58ea736df6d06727583f51',
    messagingSenderId: '669691510276',
    projectId: 'nasaapp-446811',
    authDomain: 'nasaapp-446811.firebaseapp.com',
    databaseURL: 'https://nasaapp-446811-default-rtdb.firebaseio.com',
    storageBucket: 'nasaapp-446811.firebasestorage.app',
    measurementId: 'G-ZXCMYHFXRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRFqoSpQhxNuxAlwJFxUwsfnQANuuzCuI',
    appId: '1:669691510276:android:7ed381bcdfbb3b64583f51',
    messagingSenderId: '669691510276',
    projectId: 'nasaapp-446811',
    databaseURL: 'https://nasaapp-446811-default-rtdb.firebaseio.com',
    storageBucket: 'nasaapp-446811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxEBsHqC4_goUsyS5tr04op9nTxwZzwi8',
    appId: '1:669691510276:ios:483fee9a97b9ab74583f51',
    messagingSenderId: '669691510276',
    projectId: 'nasaapp-446811',
    databaseURL: 'https://nasaapp-446811-default-rtdb.firebaseio.com',
    storageBucket: 'nasaapp-446811.firebasestorage.app',
    iosBundleId: 'com.example.nasapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxEBsHqC4_goUsyS5tr04op9nTxwZzwi8',
    appId: '1:669691510276:ios:483fee9a97b9ab74583f51',
    messagingSenderId: '669691510276',
    projectId: 'nasaapp-446811',
    databaseURL: 'https://nasaapp-446811-default-rtdb.firebaseio.com',
    storageBucket: 'nasaapp-446811.firebasestorage.app',
    iosBundleId: 'com.example.nasapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGajcFJDnxFwCyg1C7HW9iQtb-ElZilts',
    appId: '1:669691510276:web:d8214154df6895cc583f51',
    messagingSenderId: '669691510276',
    projectId: 'nasaapp-446811',
    authDomain: 'nasaapp-446811.firebaseapp.com',
    databaseURL: 'https://nasaapp-446811-default-rtdb.firebaseio.com',
    storageBucket: 'nasaapp-446811.firebasestorage.app',
    measurementId: 'G-821HB0G31S',
  );
}
